# Generated by Django 4.1.7 on 2023-04-17 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("accounts", "0004_alter_userprofile_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.region",
            ),
        ),
    ]
