# Generated by Django 4.1.7 on 2023-04-03 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dailyletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 3, 18, 59, 40, 825339, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyletter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
