version: "3.9"

services:
  shoponline_service:
    depends_on:
      - db_postgres
    image: mykytareva/shop-online:0.0.3
    hostname: shoponline_service
    container_name: shoponline_service
    ports:
      - "8000:8000"
    env_file:
        - .dockerenv
    networks:
        - my-net

  db_postgres:
    image: postgres:14.3-alpine
    hostname: db_postgres
    container_name: db_postgres
    restart: on-failure
    env_file:
      - .dockerenv
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    networks:
      - my-net
  nginx:
    depends_on:
      - shoponline_service
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../app/static:/static
      - ../app/media:/media
    networks:
      - my-net
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-net

networks:
  my-net:
    external: true

volumes:
  db-postgres:
    driver: local
