# Generated by Django 4.1.7 on 2023-05-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_item_price'),
        ('orders', '0002_alter_order_total_paid_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shops',
            field=models.ManyToManyField(blank=True, to='shop.shop'),
        ),
    ]
