# Generated by Django 4.1.7 on 2023-05-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shoporder'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
