# Generated by Django 4.1.7 on 2023-05-16 08:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_shoporder_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoporder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 5, 15, 8, 53, 20, 619490, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shoporder",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
