# Generated by Django 4.1.7 on 2023-05-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_shoporder_options_remove_order_shops"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoporder",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("In Process", "In Process"),
                    ("Sent", "Sent"),
                ],
                default="new",
                max_length=50,
            ),
        ),
    ]
