# Generated by Django 4.1.7 on 2023-05-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_shoporder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoporder",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("In Process", "In Process"),
                    ("Sent", "Sent"),
                ],
                default="New",
                max_length=50,
            ),
        ),
    ]
