# Generated by Django 4.1.7 on 2023-04-18 12:36

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_item_wish_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.shop_avatar),
        ),
    ]
