# Generated by Django 4.1.7 on 2023-04-18 14:42

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_shop_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="picture",
            new_name="avatar",
        ),
        migrations.AddField(
            model_name="shop",
            name="cover_photo",
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.shop_cover),
        ),
    ]
