# Generated by Django 4.1.7 on 2023-04-11 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_user_alter_shop_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='itemimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 11, 8, 24, 40, 103338, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
