# Generated by Django 4.1.7 on 2023-05-07 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_rename_picture_shop_avatar_shop_cover_photo"),
        ("cart", "0002_alter_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="shop.item",
            ),
        ),
    ]
